#!/usr/bin/env python3
"""Bundle player CSVs and analysis notes from ../data into webapp/data/players-data.js.

The output is a plain JS file (not JSON) so the web app works from file:// with no
server and no fetch/CORS concerns. Re-run this whenever the CSVs or notes change.
"""
import csv
import json
import os
import re
import sys
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(HERE, "..", "data")
OUT_PATH = os.path.join(HERE, "data", "players-data.js")

# Scoring format -> CSV file (matches archive/go-tool/loader.go getPlayerDataFilename)
FORMATS = {
    "STD": "std_with_depth.csv",
    "0.5PPR": "0.5_ppr_with_depth.csv",
    "PPR": "ppr_with_depth.csv",
}

# Matches archive/go-tool/loader.go nameCleaner: strips Jr./Sr./II/III/IV/V suffixes
SUFFIX_RE = re.compile(r"\s+(?:Jr\.|Sr\.|II|III|IV|V)$")


def clean_name(name: str) -> str:
    return SUFFIX_RE.sub("", name.strip()).strip()


def load_format(path: str):
    players = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        required = {"Rank", "Player", "Team", "Bye", "POS", "ESPN_Rank", "Sleeper_Rank"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            sys.exit(f"ERROR: {path} missing columns: {sorted(missing)}")
        for row in reader:
            name = (row["Player"] or "").strip()
            if not name:
                continue
            try:
                rank_num = float(row["Rank"])
            except (TypeError, ValueError):
                rank_num = 9999.0
            players.append({
                "name": name,
                "team": (row["Team"] or "").strip(),
                "pos": (row["POS"] or "").strip(),
                "bye": (row["Bye"] or "").strip(),
                "rank": (row["Rank"] or "").strip(),
                "rankNum": rank_num,
                "espn": (row["ESPN_Rank"] or "").strip(),
                "sleeper": (row["Sleeper_Rank"] or "").strip(),
            })
    players.sort(key=lambda p: p["rankNum"])
    return players


def load_notes():
    notes = {}
    analysis_dir = os.path.join(DATA_DIR, "notes")
    for fn in sorted(os.listdir(analysis_dir)):
        if not fn.endswith(".md"):
            continue
        with open(os.path.join(analysis_dir, fn), encoding="utf-8") as f:
            content = f.read()
        # Draft status lives in localStorage in the web app; drop stale markers
        lines = [l for l in content.split("\n") if not l.strip().startswith("# To Draft:")]
        notes[fn[:-3]] = "\n".join(lines).strip()
    return notes


def main():
    formats = {}
    for fmt, fname in FORMATS.items():
        path = os.path.join(DATA_DIR, "ranks", fname)
        if not os.path.exists(path):
            sys.exit(f"ERROR: missing CSV {path}")
        formats[fmt] = load_format(path)
        print(f"{fmt}: {len(formats[fmt])} players from {fname}")

    notes = load_notes()
    print(f"notes: {len(notes)} analysis files")

    # Same check as the legacy Go tool: every player should have a note file
    missing = []
    for fmt, players in formats.items():
        for p in players:
            if clean_name(p["name"]) not in notes:
                missing.append(f"{p['name']} ({fmt})")
    if missing:
        print(f"WARNING: {len(missing)} players without note files (app shows 'No note'):")
        for m in sorted(set(missing)):
            print(f"  - {m}")

    data = {
        "generatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "formats": formats,
        "notes": notes,
    }

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("// Generated by build_data.py — do not edit by hand.\n")
        f.write("window.FF_DATA = ")
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    size_mb = os.path.getsize(OUT_PATH) / (1024 * 1024)
    print(f"wrote {OUT_PATH} ({size_mb:.2f} MB)")


if __name__ == "__main__":
    main()
